x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  random_service:
    container_name: random_service
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    restart: on-failure
    volumes:
      - ../../config/config-docker.yaml:/usr/app/config/config.yaml
      - random_service_logs:/tmp/log/
    ports:
      - 8069:8069
      - 8071:8071 # metrics
    logging:
      <<: *loki-logging
    networks:
      - service

  client:
    container_name: client
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.client
    restart: on-failure
    volumes:
      - ../../config/config-docker.yaml:/usr/app/config/config.yaml
    ports:
      - 8070:8070
    networks:
      - service
    logging:
      <<: *loki-logging
    depends_on:
      random_service:
        condition: service_started

  # --- Uncomment to enable Grafana Beyla auto instrumentation.
  # --- This must be run on a Linux machine with ebpf enabled.
  #
  # random_service_trace:
  #   container_name: random_service_trace
  #   image: grafana/beyla:latest
  #   pid: "service:random_service"
  #   privileged: true
  #   restart: on-failure
  #   volumes:
  #     - /sys/kernel/security:/sys/kernel/security
  #   environment:
  #     BEYLA_PRINT_TRACES: true
  #     BEYLA_OPEN_PORT: "8069"
  #     BEYLA_SERVICE_NAMESPACE: "soa"
  #     OTEL_SERVICE_NAME: "random_service_beyla"
  #     # BEYLA_LOG_LEVEL: "DEBUG"
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
  #     OTEL_EXPORTER_OTLP_TRACES_INSECURE: true
  #     OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  #     BEYLA_OTEL_INSECURE_SKIP_VERIFY: true
  #     BEYLA_OTEL_TRACES_INSTRUMENTATIONS: grpc
  #   network_mode: "service:random_service"
  #   depends_on:
  #     random_service:
  #       condition: service_started
  #
  # client_trace:
  #   container_name: client_trace
  #   image: grafana/beyla:latest
  #   privileged: true
  #   restart: on-failure
  #   volumes:
  #     - /sys/kernel/security:/sys/kernel/security
  #   environment:
  #     BEYLA_PRINT_TRACES: true
  #     BEYLA_OPEN_PORT: "8070"
  #     BEYLA_SERVICE_NAMESPACE: "soa"
  #     OTEL_SERVICE_NAME: "random_client_beyla"
  #     # BEYLA_LOG_LEVEL: "DEBUG"
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
  #     OTEL_EXPORTER_OTLP_TRACES_INSECURE: true
  #     OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  #     BEYLA_OTEL_INSECURE_SKIP_VERIFY: true
  #     BEYLA_OTEL_TRACES_INSTRUMENTATIONS: http
  #   pid: "service:client"
  #   network_mode: "service:client"
  #   depends_on:
  #     client:
  #       condition: service_started

  loki_read:
    image: grafana/loki:3.3.2
    command: "-config.file=/etc/loki/loki.yaml -target=read"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
    depends_on:
      - minio
    networks:
      - observability

  loki_write:
    image: grafana/loki:3.3.2
    command: "-config.file=/etc/loki/loki.yaml -target=write"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
    depends_on:
      - minio
    networks:
      - observability

  loki_backend:
    image: grafana/loki:3.3.2
    command: "-config.file=/etc/loki/loki.yaml -target=backend -legacy-read-mode=false"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
    depends_on:
      - load-balancer
      - minio
    networks:
      - observability

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        mkdir -p /data/mimir && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - minio-data:/data
    networks:
      - observability

  grafana:
    image: grafana/grafana:11.4.0
    pull_policy: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_LOG_MODE=console
      - GF_LOG_LEVEL=critical
    volumes:
      - ./config/grafana-provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      # Explicitly list the dashboards we want to show in the demo. We intentionally exclude dashboards that require
      # Kubernetes metrics (eg. resources or networking) and other services not available in the demo (eg. Grafana Loki).
      - ./config/mimir-mixin-compiled/dashboards/mimir-alertmanager.json:/var/lib/grafana/dashboards/mimir-alertmanager.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-compactor.json:/var/lib/grafana/dashboards/mimir-compactor.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-object-store.json:/var/lib/grafana/dashboards/mimir-object-store.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-overrides.json:/var/lib/grafana/dashboards/mimir-overrides.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-queries.json:/var/lib/grafana/dashboards/mimir-queries.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-reads.json:/var/lib/grafana/dashboards/mimir-reads.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-ruler.json:/var/lib/grafana/dashboards/mimir-ruler.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-tenants.json:/var/lib/grafana/dashboards/mimir-tenants.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-top-tenants.json:/var/lib/grafana/dashboards/mimir-top-tenants.json:ro
      - ./config/mimir-mixin-compiled/dashboards/mimir-writes.json:/var/lib/grafana/dashboards/mimir-writes.json:ro
    ports:
      - 9000:3000
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v3.0.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=error
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/mimir-mixin-compiled/rules.yaml:/etc/prometheus/rules.yaml
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    networks:
      - observability

  load-balancer:
    image: nginx:1.27-alpine3.20
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    networks:
      - observability

  mimir-1:
    image: grafana/mimir:2.14.2
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-1-data:/data
    networks:
      - observability

  mimir-2:
    image: grafana/mimir:2.14.2
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-2
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-2-data:/data
    networks:
      - observability

  mimir-3:
    image: grafana/mimir:2.14.2
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-3
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-3-data:/data
    networks:
      - observability

  tempo:
    image: grafana/tempo:2.6.1
    command:
      - "-config.file=/etc/tempo.yaml"
      - "-mem-ballast-size-mbs=1024"
      - "-config.expand-env=true"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    environment:
      REMOTE_WRITE_HOST: load-balancer:9009
    networks:
      - observability

  agent:
    image: grafana/alloy:v1.5.1
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy
      - random_service_logs:/tmp/log/
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--stability.level=public-preview",
        "/etc/alloy/config.alloy",
      ]
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
      - "tempo"
      - "loki_backend"
      - "loki_read"
      - "loki_write"
      - "load-balancer"
      - "random_service"
      - "client"
    networks:
      - service
      - observability

volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
  minio-data:
  tempo_data:
  loki_data:
  random_service_logs:

# Network
networks:
  service:
    name: service
  observability:
    name: observability
