version: '3.9'

services:
    random_service:
        container_name: random_service
        build:
          context: ../../
          dockerfile: deploy/docker/Dockerfile
        restart: on-failure
        volumes:
            - ./config/config-docker.yaml:/usr/app/config/config.yaml
        ports:
            - 8069:8069
            - 8071:8071 # metrics
        networks:
            - service

    client:
        container_name: client
        build:
          context: ../../
          dockerfile: deploy/docker/Dockerfile.client
        restart: on-failure
        ports:
            - 8070:8070
        networks:
            - service
        depends_on:
            - random_service

# Network
networks:
    service:
        name: service