multitenancy_enabled: false
usage_report:
  reporting_enabled: true
compactor:
  compaction:
    block_retention: 24h
distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: null
        thrift_binary:
          endpoint: null
        thrift_compact:
          endpoint: null
        thrift_http:
          endpoint: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
ingester: {}
server:
  http_listen_port: 3100
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
querier: {}
query_frontend: {}
overrides:
  metrics_generator_processors:
    - "service-graphs"
    - "span-metrics"
metrics_generator:
  storage:
    path: "/tmp/tempo"
    remote_write:
      - url: http://${REMOTE_WRITE_HOST:-localhost:9009}/api/v1/push
        headers:
          X-Scope-OrgID: demo
