server:
  bind_addr: 127.0.0.1:8069
  name: "random"

client:
  bind_addr: 127.0.0.1:8070
  server_addr: 127.0.0.1:8069

metrics:
  bind_addr: 127.0.0.1:8071

tracing:
  otlp:
    collector_url:
    insecure: true
