# You can set the value of any configuration to environment variable
# by using the syntax ${ENV_VAR_NAME}. For example, the following
# configuration will set the value of the server.bind_addr to the
# value of the environment variable SERVER_BIND_ADDR:
#
# server:
#   bind_addr: ${SERVER_BIND_ADDR}

server:
  bind_addr: 0.0.0.0:8069
  name: "random_service"

client:
  bind_addr: 0.0.0.0:8070
  server_addr: random_service:8069
  name: "random_client"

logs:
  level: debug # can be debug, info, warn, error, or fatal
  development: false
  path: /tmp/log/ # Leave empty to disable file logging

metrics:
  bind_addr: 0.0.0.0:8071

tracing:
  otlp:
    enabled: true
    collector_url: agent:4317
    insecure: true
