// Code generated by mockery v2.20.0. DO NOT EDIT.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockRandomServiceClient is an autogenerated mock type for the RandomServiceClient type
type MockRandomServiceClient struct {
	mock.Mock
}

type MockRandomServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRandomServiceClient) EXPECT() *MockRandomServiceClient_Expecter {
	return &MockRandomServiceClient_Expecter{mock: &_m.Mock}
}

// GetRandNumber provides a mock function with given fields: ctx, in, opts
func (_m *MockRandomServiceClient) GetRandNumber(ctx context.Context, in *GetRandNumberRequest, opts ...grpc.CallOption) (*GetRandNumberReply, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *GetRandNumberReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetRandNumberRequest, ...grpc.CallOption) (*GetRandNumberReply, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetRandNumberRequest, ...grpc.CallOption) *GetRandNumberReply); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetRandNumberReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetRandNumberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRandomServiceClient_GetRandNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandNumber'
type MockRandomServiceClient_GetRandNumber_Call struct {
	*mock.Call
}

// GetRandNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetRandNumberRequest
//   - opts ...grpc.CallOption
func (_e *MockRandomServiceClient_Expecter) GetRandNumber(ctx interface{}, in interface{}, opts ...interface{}) *MockRandomServiceClient_GetRandNumber_Call {
	return &MockRandomServiceClient_GetRandNumber_Call{Call: _e.mock.On("GetRandNumber",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRandomServiceClient_GetRandNumber_Call) Run(run func(ctx context.Context, in *GetRandNumberRequest, opts ...grpc.CallOption)) *MockRandomServiceClient_GetRandNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*GetRandNumberRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockRandomServiceClient_GetRandNumber_Call) Return(_a0 *GetRandNumberReply, _a1 error) *MockRandomServiceClient_GetRandNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRandomServiceClient_GetRandNumber_Call) RunAndReturn(run func(context.Context, *GetRandNumberRequest, ...grpc.CallOption) (*GetRandNumberReply, error)) *MockRandomServiceClient_GetRandNumber_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRandomServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRandomServiceClient creates a new instance of MockRandomServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRandomServiceClient(t mockConstructorTestingTNewMockRandomServiceClient) *MockRandomServiceClient {
	mock := &MockRandomServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
