// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: random.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeedNum       int64                  `protobuf:"varint,1,opt,name=SeedNum,proto3" json:"SeedNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandNumberRequest) Reset() {
	*x = GetRandNumberRequest{}
	mi := &file_random_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandNumberRequest) ProtoMessage() {}

func (x *GetRandNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_random_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandNumberRequest.ProtoReflect.Descriptor instead.
func (*GetRandNumberRequest) Descriptor() ([]byte, []int) {
	return file_random_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandNumberRequest) GetSeedNum() int64 {
	if x != nil {
		return x.SeedNum
	}
	return 0
}

type GetRandNumberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int64                  `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandNumberReply) Reset() {
	*x = GetRandNumberReply{}
	mi := &file_random_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandNumberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandNumberReply) ProtoMessage() {}

func (x *GetRandNumberReply) ProtoReflect() protoreflect.Message {
	mi := &file_random_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandNumberReply.ProtoReflect.Descriptor instead.
func (*GetRandNumberReply) Descriptor() ([]byte, []int) {
	return file_random_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandNumberReply) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_random_proto protoreflect.FileDescriptor

var file_random_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x65, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x53, 0x65, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x5c, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x68, 0x74, 0x68, 0x6f, 0x6e, 0x67, 0x35, 0x38, 0x32, 0x30,
	0x30, 0x30, 0x2f, 0x53, 0x4f, 0x41, 0x2d, 0x34, 0x30, 0x34, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_random_proto_rawDescOnce sync.Once
	file_random_proto_rawDescData = file_random_proto_rawDesc
)

func file_random_proto_rawDescGZIP() []byte {
	file_random_proto_rawDescOnce.Do(func() {
		file_random_proto_rawDescData = protoimpl.X.CompressGZIP(file_random_proto_rawDescData)
	})
	return file_random_proto_rawDescData
}

var file_random_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_random_proto_goTypes = []any{
	(*GetRandNumberRequest)(nil), // 0: random.GetRandNumberRequest
	(*GetRandNumberReply)(nil),   // 1: random.GetRandNumberReply
}
var file_random_proto_depIdxs = []int32{
	0, // 0: random.RandomService.GetRandNumber:input_type -> random.GetRandNumberRequest
	1, // 1: random.RandomService.GetRandNumber:output_type -> random.GetRandNumberReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_random_proto_init() }
func file_random_proto_init() {
	if File_random_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_random_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_random_proto_goTypes,
		DependencyIndexes: file_random_proto_depIdxs,
		MessageInfos:      file_random_proto_msgTypes,
	}.Build()
	File_random_proto = out.File
	file_random_proto_rawDesc = nil
	file_random_proto_goTypes = nil
	file_random_proto_depIdxs = nil
}
