name: Pre-commit

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  preCommitValidation:
    name: Pre Commit Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # v4.0.0

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.1.0
