name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: ${{ github.repository }}

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Log in to the Container registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: version
        run: |
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build and push server
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        id: push-server
        with:
          context: .
          file: deploy/docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/soa-404-server:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push server
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        id: push-client
        with:
          context: .
          file: deploy/docker/Dockerfile.client
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/soa-404-client:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Attest build provenance server
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        id: attest-server
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/soa-404-server
          subject-digest: ${{ steps.push-server.outputs.digest }}
          push-to-registry: true

      - name: Attest build provenance client
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
        id: attest-client
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/soa-404-client
          subject-digest: ${{ steps.push-client.outputs.digest }}
          push-to-registry: true
